#ifndef __UCONFIG_LOCAL_H__
#define __UCONFIG_LOCAL_H__

#define U_LIB_SUFFIX_C_NAME _android

#define U_DEF_ICU_ENTRY_POINT_RENAME(x,z) x ## z
#define U_DEF2_ICU_ENTRY_POINT_RENAME(x,z) U_DEF_ICU_ENTRY_POINT_RENAME(x,z)
#define U_ICU_ENTRY_POINT_RENAME(x)    U_DEF2_ICU_ENTRY_POINT_RENAME(x,U_LIB_SUFFIX_C_NAME)

#endif
