/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MonkeyProcess */

#ifndef _Included_MonkeyProcess
#define _Included_MonkeyProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MonkeyProcess
 * Method:    createNewProcessSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_commands_monkey_MonkeyProcess_createNewProcessSession(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
