/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* The following table shows the changes of ICU4C stable C APIs from ICU 44 to
 * ICU 54.
 *
 * ICU 44 is the version shipped in Gingerbread (2.3.3) devices, which is also
 * the minimum version supported by NDK ICU. NDK provides support for stable C
 * APIs based on ICU 44, minus the deprecated ones in later versions for
 * compatability.
 *
 * The table can be regenerated by 'gen-icu4c-api-matrix.py' tool.
 *
 * Changes of ICU4C stable C APIs
 *
ICU VERSIONS                            |  44  46  48  49  50  51  52  53  54
--------------------------------------------------------------------------------
  <unicode/ucsdet.h>                    |
ucsdet_open                             |
ucsdet_close                            |
ucsdet_setText                          |
ucsdet_setDeclaredEncoding              |
ucsdet_detect                           |
ucsdet_detectAll                        |
ucsdet_getName                          |
ucsdet_getConfidence                    |
ucsdet_getLanguage                      |
ucsdet_getUChars                        |
ucsdet_getAllDetectableCharsets         |
ucsdet_isInputFilterEnabled             |
ucsdet_enableInputFilter                |
                                        |
  <unicode/uversion.h>                  |
u_versionFromString                     |
u_versionFromUString                    |
u_versionToString                       |
u_getVersion                            |
                                        |
  <unicode/udatpg.h>                    |
udatpg_open                             |
udatpg_openEmpty                        |
udatpg_close                            |
udatpg_clone                            |
udatpg_getBestPattern                   |
udatpg_getSkeleton                      |
udatpg_getBaseSkeleton                  |
udatpg_addPattern                       |
udatpg_setAppendItemFormat              |
udatpg_getAppendItemFormat              |
udatpg_setAppendItemName                |
udatpg_getAppendItemName                |
udatpg_setDateTimeFormat                |
udatpg_getDateTimeFormat                |
udatpg_setDecimal                       |
udatpg_getDecimal                       |
udatpg_replaceFieldTypes                |
udatpg_openSkeletons                    |
udatpg_openBaseSkeletons                |
udatpg_getPatternForSkeleton            |
udatpg_getBestPatternWithOptions        |  -   +   +   +   +   +   +   +   +
udatpg_replaceFieldTypesWithOptions     |  -   +   +   +   +   +   +   +   +
                                        |
  <unicode/udata.h>                     |
udata_open                              |
udata_openChoice                        |
udata_close                             |
udata_getMemory                         |
udata_getInfo                           |
udata_setCommonData                     |
udata_setAppData                        |
udata_setFileAccess                     |
                                        |
  <unicode/uset.h>                      |
uset_openEmpty                          |
uset_open                               |
uset_openPattern                        |
uset_openPatternOptions                 |
uset_close                              |
uset_clone                              |
uset_isFrozen                           |
uset_freeze                             |
uset_cloneAsThawed                      |
uset_set                                |
uset_applyPattern                       |
uset_applyIntPropertyValue              |
uset_applyPropertyAlias                 |
uset_resemblesPattern                   |
uset_toPattern                          |
uset_add                                |
uset_addAll                             |
uset_addRange                           |
uset_addString                          |
uset_addAllCodePoints                   |
uset_remove                             |
uset_removeRange                        |
uset_removeString                       |
uset_removeAll                          |
uset_retain                             |
uset_retainAll                          |
uset_compact                            |
uset_complement                         |
uset_complementAll                      |
uset_clear                              |
uset_closeOver                          |
uset_removeAllStrings                   |
uset_isEmpty                            |
uset_contains                           |
uset_containsRange                      |
uset_containsString                     |
uset_indexOf                            |
uset_charAt                             |
uset_size                               |
uset_getItemCount                       |
uset_getItem                            |
uset_containsAll                        |
uset_containsAllCodePoints              |
uset_containsNone                       |
uset_containsSome                       |
uset_span                               |
uset_spanBack                           |
uset_spanUTF8                           |
uset_spanBackUTF8                       |
uset_equals                             |
uset_serialize                          |
uset_getSerializedSet                   |
uset_setSerializedToOne                 |
uset_serializedContains                 |
uset_getSerializedRangeCount            |
uset_getSerializedRange                 |
                                        |
  <unicode/utf8.h>                      |
utf8_nextCharSafeBody                   |  -   -   -   +   +   +   +   +   +
utf8_appendCharSafeBody                 |  -   -   -   +   +   +   +   +   +
utf8_prevCharSafeBody                   |  -   -   -   +   +   +   +   +   +
utf8_back1SafeBody                      |  -   -   -   +   +   +   +   +   +
                                        |
  <unicode/ugender.h>                   |
ugender_getInstance                     |  -   -   -   -   -   -   +   +   +
ugender_getListGender                   |  -   -   -   -   -   -   +   +   +
                                        |
  <unicode/utmscale.h>                  |
utmscale_getTimeScaleValue              |
utmscale_fromInt64                      |
utmscale_toInt64                        |
                                        |
  <unicode/umsg.h>                      |
u_formatMessage                         |
u_vformatMessage                        |
u_parseMessage                          |
u_vparseMessage                         |
u_formatMessageWithError                |
u_vformatMessageWithError               |
u_parseMessageWithError                 |
u_vparseMessageWithError                |
umsg_open                               |
umsg_close                              |
umsg_clone                              |
umsg_setLocale                          |
umsg_getLocale                          |
umsg_applyPattern                       |
umsg_toPattern                          |
umsg_format                             |
umsg_vformat                            |
umsg_parse                              |
umsg_vparse                             |
umsg_autoQuoteApostrophe                |
                                        |
  <unicode/ushape.h>                    |
u_shapeArabic                           |
                                        |
  <unicode/ustring.h>                   |
u_strlen                                |
u_countChar32                           |
u_strHasMoreChar32Than                  |
u_strcat                                |
u_strncat                               |
u_strstr                                |
u_strFindFirst                          |
u_strchr                                |
u_strchr32                              |
u_strrstr                               |
u_strFindLast                           |
u_strrchr                               |
u_strrchr32                             |
u_strpbrk                               |
u_strcspn                               |
u_strspn                                |
u_strtok_r                              |
u_strcmp                                |
u_strcmpCodePointOrder                  |
u_strCompare                            |
u_strCompareIter                        |
u_strCaseCompare                        |
u_strncmp                               |
u_strncmpCodePointOrder                 |
u_strcasecmp                            |
u_strncasecmp                           |
u_memcasecmp                            |
u_strcpy                                |
u_strncpy                               |
u_uastrcpy                              |
u_uastrncpy                             |
u_austrcpy                              |
u_austrncpy                             |
u_memcpy                                |
u_memmove                               |
u_memset                                |
u_memcmp                                |
u_memcmpCodePointOrder                  |
u_memchr                                |
u_memchr32                              |
u_memrchr                               |
u_memrchr32                             |
u_unescape                              |
u_unescapeAt                            |
u_strToUpper                            |
u_strToLower                            |
u_strToTitle                            |
u_strFoldCase                           |
u_strToWCS                              |
u_strFromWCS                            |
u_strToUTF8                             |
u_strFromUTF8                           |
u_strToUTF8WithSub                      |
u_strFromUTF8WithSub                    |
u_strFromUTF8Lenient                    |
u_strToUTF32                            |
u_strFromUTF32                          |
u_strToUTF32WithSub                     |
u_strFromUTF32WithSub                   |
u_strToJavaModifiedUTF8                 |  -   +   +   +   +   +   +   +   +
u_strFromJavaModifiedUTF8WithSub        |  -   +   +   +   +   +   +   +   +
                                        |
  <unicode/udat.h>                      |
udat_open                               |
udat_close                              |
udat_clone                              |
udat_format                             |
udat_parse                              |
udat_parseCalendar                      |
udat_isLenient                          |
udat_setLenient                         |
udat_getCalendar                        |
udat_setCalendar                        |
udat_getNumberFormat                    |
udat_setNumberFormat                    |
udat_getAvailable                       |
udat_countAvailable                     |
udat_get2DigitYearStart                 |
udat_set2DigitYearStart                 |
udat_toPattern                          |
udat_applyPattern                       |
udat_getSymbols                         |
udat_countSymbols                       |
udat_setSymbols                         |
udat_getLocaleByType                    |
udat_toCalendarDateField                |  -   +   +   +   +   +   +   +   +
                                        |
  <unicode/ucat.h>                      |
u_catopen                               |
u_catclose                              |
u_catgets                               |
                                        |
  <unicode/ucnv.h>                      |
ucnv_compareNames                       |
ucnv_open                               |
ucnv_openU                              |
ucnv_openCCSID                          |
ucnv_openPackage                        |
ucnv_safeClone                          |
ucnv_close                              |
ucnv_getSubstChars                      |
ucnv_setSubstChars                      |
ucnv_setSubstString                     |
ucnv_getInvalidChars                    |
ucnv_getInvalidUChars                   |
ucnv_reset                              |
ucnv_resetToUnicode                     |
ucnv_resetFromUnicode                   |
ucnv_getMaxCharSize                     |
ucnv_getMinCharSize                     |
ucnv_getDisplayName                     |
ucnv_getName                            |
ucnv_getCCSID                           |
ucnv_getPlatform                        |
ucnv_getType                            |
ucnv_getStarters                        |
ucnv_getUnicodeSet                      |
ucnv_getToUCallBack                     |
ucnv_getFromUCallBack                   |
ucnv_setToUCallBack                     |
ucnv_setFromUCallBack                   |
ucnv_fromUnicode                        |
ucnv_toUnicode                          |
ucnv_fromUChars                         |
ucnv_toUChars                           |
ucnv_getNextUChar                       |
ucnv_convertEx                          |
ucnv_convert                            |
ucnv_toAlgorithmic                      |
ucnv_fromAlgorithmic                    |
ucnv_flushCache                         |
ucnv_countAvailable                     |
ucnv_getAvailableName                   |
ucnv_openAllNames                       |
ucnv_countAliases                       |
ucnv_getAlias                           |
ucnv_getAliases                         |
ucnv_openStandardNames                  |
ucnv_countStandards                     |
ucnv_getStandard                        |
ucnv_getStandardName                    |
ucnv_getCanonicalName                   |
ucnv_getDefaultName                     |
ucnv_setDefaultName                     |
ucnv_fixFileSeparator                   |
ucnv_isAmbiguous                        |
ucnv_setFallback                        |
ucnv_usesFallback                       |
ucnv_detectUnicodeSignature             |
ucnv_fromUCountPending                  |
ucnv_toUCountPending                    |
ucnv_isFixedWidth                       |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/ucasemap.h>                  |
ucasemap_open                           |
ucasemap_close                          |
ucasemap_getLocale                      |
ucasemap_getOptions                     |
ucasemap_setLocale                      |
ucasemap_setOptions                     |
ucasemap_getBreakIterator               |
ucasemap_setBreakIterator               |
ucasemap_toTitle                        |
ucasemap_utf8ToLower                    |
ucasemap_utf8ToUpper                    |
ucasemap_utf8ToTitle                    |
ucasemap_utf8FoldCase                   |
                                        |
  <unicode/upluralrules.h>              |
uplrules_open                           |  -   -   -   -   +   +   +   +   +
uplrules_close                          |  -   -   -   -   +   +   +   +   +
uplrules_select                         |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/ulocdata.h>                  |
ulocdata_open                           |
ulocdata_close                          |
ulocdata_setNoSubstitute                |
ulocdata_getNoSubstitute                |
ulocdata_getExemplarSet                 |
ulocdata_getDelimiter                   |
ulocdata_getMeasurementSystem           |
ulocdata_getPaperSize                   |
ulocdata_getCLDRVersion                 |
ulocdata_getLocaleDisplayPattern        |
ulocdata_getLocaleSeparator             |
                                        |
  <unicode/uiter.h>                     |
uiter_current32                         |
uiter_next32                            |
uiter_previous32                        |
uiter_getState                          |
uiter_setState                          |
uiter_setString                         |
uiter_setUTF16BE                        |
uiter_setUTF8                           |
                                        |
  <unicode/ucurr.h>                     |
ucurr_forLocale                         |
ucurr_register                          |
ucurr_unregister                        |
ucurr_getName                           |
ucurr_getPluralName                     |
ucurr_getDefaultFractionDigits          |
ucurr_getRoundingIncrement              |
ucurr_openISOCurrencies                 |
ucurr_countCurrencies                   |
ucurr_forLocaleAndDate                  |
ucurr_getKeywordValuesForLocale         |
ucurr_isAvailable                       |  -   -   -   -   +   +   +   +   +
ucurr_getNumericCode                    |  -   -   -   -   -   +   +   +   +
                                        |
  <unicode/ucnvsel.h>                   |
ucnvsel_open                            |
ucnvsel_close                           |
ucnvsel_openFromSerialized              |
ucnvsel_serialize                       |
ucnvsel_selectForString                 |
ucnvsel_selectForUTF8                   |
                                        |
  <unicode/ucnv_err.h>                  |
UCNV_FROM_U_CALLBACK_STOP               |
UCNV_TO_U_CALLBACK_STOP                 |
UCNV_FROM_U_CALLBACK_SKIP               |
UCNV_FROM_U_CALLBACK_SUBSTITUTE         |
UCNV_FROM_U_CALLBACK_ESCAPE             |
UCNV_TO_U_CALLBACK_SKIP                 |
UCNV_TO_U_CALLBACK_SUBSTITUTE           |
UCNV_TO_U_CALLBACK_ESCAPE               |
                                        |
  <unicode/udateintervalformat.h>       |
udtitvfmt_open                          |  -   -   -   -   +   +   +   +   +
udtitvfmt_close                         |  -   -   -   -   +   +   +   +   +
udtitvfmt_format                        |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/uldnames.h>                  |
uldn_open                               |  -   +   +   +   +   +   +   +   +
uldn_close                              |  -   +   +   +   +   +   +   +   +
uldn_getLocale                          |  -   +   +   +   +   +   +   +   +
uldn_getDialectHandling                 |  -   +   +   +   +   +   +   +   +
uldn_localeDisplayName                  |  -   +   +   +   +   +   +   +   +
uldn_languageDisplayName                |  -   +   +   +   +   +   +   +   +
uldn_scriptDisplayName                  |  -   +   +   +   +   +   +   +   +
uldn_scriptCodeDisplayName              |  -   +   +   +   +   +   +   +   +
uldn_regionDisplayName                  |  -   +   +   +   +   +   +   +   +
uldn_variantDisplayName                 |  -   +   +   +   +   +   +   +   +
uldn_keyDisplayName                     |  -   +   +   +   +   +   +   +   +
uldn_keyValueDisplayName                |  -   +   +   +   +   +   +   +   +
uldn_openForContext                     |  -   -   -   -   -   -   -   +   +
uldn_getContext                         |  -   -   -   -   -   -   -   +   +
                                        |
  <unicode/uidna.h>                     |
uidna_toASCII                           |
uidna_toUnicode                         |
uidna_IDNToASCII                        |
uidna_IDNToUnicode                      |
uidna_compare                           |
uidna_openUTS46                         |  -   -   -   -   +   +   +   +   +
uidna_close                             |  -   -   -   -   +   +   +   +   +
uidna_labelToASCII                      |  -   -   -   -   +   +   +   +   +
uidna_labelToUnicode                    |  -   -   -   -   +   +   +   +   +
uidna_nameToASCII                       |  -   -   -   -   +   +   +   +   +
uidna_nameToUnicode                     |  -   -   -   -   +   +   +   +   +
uidna_labelToASCII_UTF8                 |  -   -   -   -   +   +   +   +   +
uidna_labelToUnicodeUTF8                |  -   -   -   -   +   +   +   +   +
uidna_nameToASCII_UTF8                  |  -   -   -   -   +   +   +   +   +
uidna_nameToUnicodeUTF8                 |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/ucol.h>                      |
ucol_open                               |
ucol_openRules                          |
ucol_openFromShortString                |  +   +   +   +   +   +   +   +   -
ucol_getContractionsAndExpansions       |
ucol_close                              |
ucol_strcoll                            |
ucol_greater                            |
ucol_greaterOrEqual                     |
ucol_equal                              |
ucol_strcollIter                        |
ucol_getStrength                        |
ucol_setStrength                        |
ucol_getDisplayName                     |
ucol_getAvailable                       |
ucol_countAvailable                     |
ucol_openAvailableLocales               |
ucol_getKeywords                        |
ucol_getKeywordValues                   |
ucol_getKeywordValuesForLocale          |
ucol_getFunctionalEquivalent            |
ucol_getRules                           |
ucol_getShortDefinitionString           |  +   +   +   +   +   +   +   +   -
ucol_normalizeShortDefinitionString     |  +   +   +   +   +   +   +   +   -
ucol_getSortKey                         |
ucol_nextSortKeyPart                    |
ucol_getBound                           |
ucol_getVersion                         |
ucol_getUCAVersion                      |
ucol_mergeSortkeys                      |
ucol_setAttribute                       |
ucol_getAttribute                       |
ucol_setVariableTop                     |  +   +   +   +   +   +   +   -   -
ucol_getVariableTop                     |
ucol_restoreVariableTop                 |  +   +   +   +   +   +   +   -   -
ucol_safeClone                          |
ucol_getRulesEx                         |
ucol_getLocaleByType                    |
ucol_getTailoredSet                     |
ucol_cloneBinary                        |
ucol_openBinary                         |
ucol_getReorderCodes                    |  -   -   -   -   +   +   +   +   +
ucol_setReorderCodes                    |  -   -   -   -   +   +   +   +   +
ucol_getEquivalentReorderCodes          |  -   -   -   -   +   +   +   +   +
ucol_strcollUTF8                        |  -   -   -   -   -   -   +   +   +
                                        |
  <unicode/uenum.h>                     |
uenum_close                             |
uenum_count                             |
uenum_unext                             |
uenum_next                              |
uenum_reset                             |
uenum_openUCharStringsEnumeration       |  -   -   -   -   -   -   +   +   +
uenum_openCharStringsEnumeration        |  -   -   -   -   -   -   +   +   +
                                        |
  <unicode/ubidi.h>                     |
ubidi_open                              |
ubidi_openSized                         |
ubidi_close                             |
ubidi_setInverse                        |
ubidi_isInverse                         |
ubidi_orderParagraphsLTR                |
ubidi_isOrderParagraphsLTR              |
ubidi_setReorderingMode                 |
ubidi_getReorderingMode                 |
ubidi_setReorderingOptions              |
ubidi_getReorderingOptions              |
ubidi_setPara                           |
ubidi_setLine                           |
ubidi_getDirection                      |
ubidi_getText                           |
ubidi_getLength                         |
ubidi_getParaLevel                      |
ubidi_countParagraphs                   |
ubidi_getParagraph                      |
ubidi_getParagraphByIndex               |
ubidi_getLevelAt                        |
ubidi_getLevels                         |
ubidi_getLogicalRun                     |
ubidi_countRuns                         |
ubidi_getVisualRun                      |
ubidi_getVisualIndex                    |
ubidi_getLogicalIndex                   |
ubidi_getLogicalMap                     |
ubidi_getVisualMap                      |
ubidi_reorderLogical                    |
ubidi_reorderVisual                     |
ubidi_invertMap                         |
ubidi_getProcessedLength                |
ubidi_getResultLength                   |
ubidi_getCustomizedClass                |
ubidi_setClassCallback                  |
ubidi_getClassCallback                  |
ubidi_writeReordered                    |
ubidi_writeReverse                      |
ubidi_setContext                        |  -   -   -   -   +   +   +   +   +
ubidi_getBaseDirection                  |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/usprep.h>                    |
usprep_open                             |
usprep_openByType                       |
usprep_close                            |
usprep_prepare                          |
                                        |
  <unicode/utrans.h>                    |
utrans_openU                            |
utrans_openInverse                      |
utrans_clone                            |
utrans_close                            |
utrans_getUnicodeID                     |
utrans_register                         |
utrans_unregisterID                     |
utrans_setFilter                        |
utrans_countAvailableIDs                |
utrans_openIDs                          |
utrans_trans                            |
utrans_transIncremental                 |
utrans_transUChars                      |
utrans_transIncrementalUChars           |
                                        |
  <unicode/ures.h>                      |
ures_open                               |
ures_openDirect                         |
ures_openU                              |
ures_close                              |
ures_getVersion                         |
ures_getLocaleByType                    |
ures_getString                          |
ures_getUTF8String                      |
ures_getBinary                          |
ures_getIntVector                       |
ures_getUInt                            |
ures_getInt                             |
ures_getSize                            |
ures_getType                            |
ures_getKey                             |
ures_resetIterator                      |
ures_hasNext                            |
ures_getNextResource                    |
ures_getNextString                      |
ures_getByIndex                         |
ures_getStringByIndex                   |
ures_getUTF8StringByIndex               |
ures_getByKey                           |
ures_getStringByKey                     |
ures_getUTF8StringByKey                 |
ures_openAvailableLocales               |
                                        |
  <unicode/icudataver.h>                |
u_getDataVersion                        |  -   -   -   -   -   +   +   +   +
                                        |
  <unicode/unorm2.h>                    |
unorm2_getInstance                      |  -   +   +   +   +   +   +   +   +
unorm2_openFiltered                     |  -   +   +   +   +   +   +   +   +
unorm2_close                            |  -   +   +   +   +   +   +   +   +
unorm2_normalize                        |  -   +   +   +   +   +   +   +   +
unorm2_normalizeSecondAndAppend         |  -   +   +   +   +   +   +   +   +
unorm2_append                           |  -   +   +   +   +   +   +   +   +
unorm2_isNormalized                     |  -   +   +   +   +   +   +   +   +
unorm2_quickCheck                       |  -   +   +   +   +   +   +   +   +
unorm2_spanQuickCheckYes                |  -   +   +   +   +   +   +   +   +
unorm2_hasBoundaryBefore                |  -   +   +   +   +   +   +   +   +
unorm2_hasBoundaryAfter                 |  -   +   +   +   +   +   +   +   +
unorm2_isInert                          |  -   +   +   +   +   +   +   +   +
unorm2_getDecomposition                 |  -   -   -   -   +   +   +   +   +
unorm2_getNFCInstance                   |  -   -   -   -   -   +   +   +   +
unorm2_getNFDInstance                   |  -   -   -   -   -   +   +   +   +
unorm2_getNFKCInstance                  |  -   -   -   -   -   +   +   +   +
unorm2_getNFKDInstance                  |  -   -   -   -   -   +   +   +   +
unorm2_getNFKCCasefoldInstance          |  -   -   -   -   -   +   +   +   +
unorm2_getRawDecomposition              |  -   -   -   -   -   +   +   +   +
unorm2_composePair                      |  -   -   -   -   -   +   +   +   +
unorm2_getCombiningClass                |  -   -   -   -   -   +   +   +   +
                                        |
  <unicode/uregion.h>                   |
uregion_getRegionFromCode               |  -   -   -   -   -   -   -   -   +
uregion_getRegionFromNumericCode        |  -   -   -   -   -   -   -   -   +
uregion_getAvailable                    |  -   -   -   -   -   -   -   -   +
uregion_areEqual                        |  -   -   -   -   -   -   -   -   +
uregion_getContainingRegion             |  -   -   -   -   -   -   -   -   +
uregion_getContainingRegionOfType       |  -   -   -   -   -   -   -   -   +
uregion_getContainedRegions             |  -   -   -   -   -   -   -   -   +
uregion_getContainedRegionsOfType       |  -   -   -   -   -   -   -   -   +
uregion_contains                        |  -   -   -   -   -   -   -   -   +
uregion_getPreferredValues              |  -   -   -   -   -   -   -   -   +
uregion_getRegionCode                   |  -   -   -   -   -   -   -   -   +
uregion_getNumericCode                  |  -   -   -   -   -   -   -   -   +
uregion_getType                         |  -   -   -   -   -   -   -   -   +
                                        |
  <unicode/uformattable.h>              |
ufmt_open                               |  -   -   -   -   -   -   -   -   +
ufmt_close                              |  -   -   -   -   -   -   -   -   +
ufmt_getType                            |  -   -   -   -   -   -   -   -   +
ufmt_isNumeric                          |  -   -   -   -   -   -   -   -   +
ufmt_getDate                            |  -   -   -   -   -   -   -   -   +
ufmt_getDouble                          |  -   -   -   -   -   -   -   -   +
ufmt_getLong                            |  -   -   -   -   -   -   -   -   +
ufmt_getInt64                           |  -   -   -   -   -   -   -   -   +
ufmt_getObject                          |  -   -   -   -   -   -   -   -   +
ufmt_getUChars                          |  -   -   -   -   -   -   -   -   +
ufmt_getArrayLength                     |  -   -   -   -   -   -   -   -   +
ufmt_getArrayItemByIndex                |  -   -   -   -   -   -   -   -   +
ufmt_getDecNumChars                     |  -   -   -   -   -   -   -   -   +
                                        |
  <unicode/utypes.h>                    |
u_errorName                             |
                                        |
  <unicode/unum.h>                      |
unum_open                               |
unum_close                              |
unum_clone                              |
unum_format                             |
unum_formatInt64                        |
unum_formatDouble                       |
unum_formatDoubleCurrency               |
unum_parse                              |
unum_parseInt64                         |
unum_parseDouble                        |
unum_parseDoubleCurrency                |
unum_applyPattern                       |
unum_getAvailable                       |
unum_countAvailable                     |
unum_getAttribute                       |
unum_setAttribute                       |
unum_getDoubleAttribute                 |
unum_setDoubleAttribute                 |
unum_getTextAttribute                   |
unum_setTextAttribute                   |
unum_toPattern                          |
unum_getSymbol                          |
unum_setSymbol                          |
unum_getLocaleByType                    |
unum_formatDecimal                      |  -   +   +   +   +   +   +   +   +
unum_parseDecimal                       |  -   +   +   +   +   +   +   +   +
unum_formatUFormattable                 |  -   -   -   -   -   -   -   -   +
unum_parseToUFormattable                |  -   -   -   -   -   -   -   -   +
                                        |
  <unicode/utrace.h>                    |
utrace_setLevel                         |
utrace_getLevel                         |
utrace_setFunctions                     |
utrace_getFunctions                     |
utrace_vformat                          |
utrace_format                           |
utrace_functionName                     |
                                        |
  <unicode/ucnv_cb.h>                   |
ucnv_cbFromUWriteBytes                  |
ucnv_cbFromUWriteSub                    |
ucnv_cbFromUWriteUChars                 |
ucnv_cbToUWriteUChars                   |
ucnv_cbToUWriteSub                      |
                                        |
  <unicode/unorm.h>                     |
unorm_normalize                         |
unorm_quickCheck                        |
unorm_quickCheckWithOptions             |
unorm_isNormalized                      |
unorm_isNormalizedWithOptions           |
unorm_next                              |
unorm_previous                          |
unorm_concatenate                       |
unorm_compare                           |
                                        |
  <unicode/uloc.h>                      |
uloc_getDefault                         |
uloc_setDefault                         |
uloc_getLanguage                        |
uloc_getScript                          |
uloc_getCountry                         |
uloc_getVariant                         |
uloc_getName                            |
uloc_canonicalize                       |
uloc_getISO3Language                    |
uloc_getISO3Country                     |
uloc_getLCID                            |
uloc_getDisplayLanguage                 |
uloc_getDisplayScript                   |
uloc_getDisplayCountry                  |
uloc_getDisplayVariant                  |
uloc_getDisplayKeyword                  |
uloc_getDisplayKeywordValue             |
uloc_getDisplayName                     |
uloc_getAvailable                       |
uloc_countAvailable                     |
uloc_getISOLanguages                    |
uloc_getISOCountries                    |
uloc_getParent                          |
uloc_getBaseName                        |
uloc_openKeywords                       |
uloc_getKeywordValue                    |
uloc_setKeywordValue                    |
uloc_getCharacterOrientation            |
uloc_getLineOrientation                 |
uloc_acceptLanguageFromHTTP             |
uloc_acceptLanguage                     |
uloc_getLocaleForLCID                   |
uloc_addLikelySubtags                   |
uloc_minimizeSubtags                    |
uloc_forLanguageTag                     |  -   -   -   -   +   +   +   +   +
uloc_toLanguageTag                      |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/uscript.h>                   |
uscript_getCode                         |
uscript_getName                         |
uscript_getShortName                    |
uscript_getScript                       |
uscript_hasScript                       |  -   -   -   -   -   +   +   +   +
uscript_getScriptExtensions             |  -   -   -   -   -   +   +   +   +
uscript_getSampleString                 |  -   -   -   -   -   -   -   +   +
uscript_getUsage                        |  -   -   -   -   -   -   -   +   +
uscript_isRightToLeft                   |  -   -   -   -   -   -   -   +   +
uscript_breaksBetweenLetters            |  -   -   -   -   -   -   -   +   +
uscript_isCased                         |  -   -   -   -   -   -   -   +   +
                                        |
  <unicode/uchar.h>                     |
u_hasBinaryProperty                     |
u_isUAlphabetic                         |
u_isULowercase                          |
u_isUUppercase                          |
u_isUWhiteSpace                         |
u_getIntPropertyValue                   |
u_getIntPropertyMinValue                |
u_getIntPropertyMaxValue                |
u_getNumericValue                       |
u_islower                               |
u_isupper                               |
u_istitle                               |
u_isdigit                               |
u_isalpha                               |
u_isalnum                               |
u_isxdigit                              |
u_ispunct                               |
u_isgraph                               |
u_isblank                               |
u_isdefined                             |
u_isspace                               |
u_isJavaSpaceChar                       |
u_isWhitespace                          |
u_iscntrl                               |
u_isISOControl                          |
u_isprint                               |
u_isbase                                |
u_charDirection                         |
u_isMirrored                            |
u_charMirror                            |
u_charType                              |
u_enumCharTypes                         |
u_getCombiningClass                     |
u_charDigitValue                        |
ublock_getCode                          |
u_charName                              |
u_getISOComment                         |  +   +   +   +   +   -   -   -   -
u_charFromName                          |
u_enumCharNames                         |
u_getPropertyName                       |
u_getPropertyEnum                       |
u_getPropertyValueName                  |
u_getPropertyValueEnum                  |
u_isIDStart                             |
u_isIDPart                              |
u_isIDIgnorable                         |
u_isJavaIDStart                         |
u_isJavaIDPart                          |
u_tolower                               |
u_toupper                               |
u_totitle                               |
u_foldCase                              |
u_digit                                 |
u_forDigit                              |
u_charAge                               |
u_getUnicodeVersion                     |
u_getFC_NFKC_Closure                    |
u_getBidiPairedBracket                  |  -   -   -   -   -   -   +   +   +
                                        |
  <unicode/utext.h>                     |
utext_close                             |
utext_openUTF8                          |
utext_openUChars                        |
utext_clone                             |
utext_equals                            |
utext_nativeLength                      |
utext_isLengthExpensive                 |
utext_char32At                          |
utext_current32                         |
utext_next32                            |
utext_previous32                        |
utext_next32From                        |
utext_previous32From                    |
utext_getNativeIndex                    |
utext_setNativeIndex                    |
utext_moveIndex32                       |
utext_getPreviousNativeIndex            |
utext_extract                           |
utext_isWritable                        |
utext_hasMetaData                       |
utext_replace                           |
utext_copy                              |
utext_freeze                            |
utext_setup                             |
                                        |
  <unicode/uregex.h>                    |
uregex_open                             |
uregex_openC                            |
uregex_close                            |
uregex_clone                            |
uregex_pattern                          |
uregex_flags                            |
uregex_setText                          |
uregex_getText                          |
uregex_matches                          |
uregex_lookingAt                        |
uregex_find                             |
uregex_findNext                         |
uregex_groupCount                       |
uregex_group                            |
uregex_start                            |
uregex_end                              |
uregex_reset                            |
uregex_setRegion                        |
uregex_regionStart                      |
uregex_regionEnd                        |
uregex_hasTransparentBounds             |
uregex_useTransparentBounds             |
uregex_hasAnchoringBounds               |
uregex_useAnchoringBounds               |
uregex_hitEnd                           |
uregex_requireEnd                       |
uregex_replaceAll                       |
uregex_replaceFirst                     |
uregex_appendReplacement                |
uregex_appendTail                       |
uregex_split                            |
uregex_setTimeLimit                     |
uregex_getTimeLimit                     |
uregex_setStackLimit                    |
uregex_getStackLimit                    |
uregex_setMatchCallback                 |
uregex_getMatchCallback                 |
uregex_openUText                        |  -   -   -   -   +   +   +   +   +
uregex_patternUText                     |  -   -   -   -   +   +   +   +   +
uregex_setUText                         |  -   -   -   -   +   +   +   +   +
uregex_getUText                         |  -   -   -   -   +   +   +   +   +
uregex_refreshUText                     |  -   -   -   -   +   +   +   +   +
uregex_matches64                        |  -   -   -   -   +   +   +   +   +
uregex_lookingAt64                      |  -   -   -   -   +   +   +   +   +
uregex_find64                           |  -   -   -   -   +   +   +   +   +
uregex_groupUText                       |  -   -   -   -   +   +   +   +   +
uregex_start64                          |  -   -   -   -   +   +   +   +   +
uregex_end64                            |  -   -   -   -   +   +   +   +   +
uregex_reset64                          |  -   -   -   -   +   +   +   +   +
uregex_setRegion64                      |  -   -   -   -   +   +   +   +   +
uregex_setRegionAndStart                |  -   -   -   -   +   +   +   +   +
uregex_regionStart64                    |  -   -   -   -   +   +   +   +   +
uregex_regionEnd64                      |  -   -   -   -   +   +   +   +   +
uregex_replaceAllUText                  |  -   -   -   -   +   +   +   +   +
uregex_replaceFirstUText                |  -   -   -   -   +   +   +   +   +
uregex_appendReplacementUText           |  -   -   -   -   +   +   +   +   +
uregex_appendTailUText                  |  -   -   -   -   +   +   +   +   +
uregex_splitUText                       |  -   -   -   -   +   +   +   +   +
uregex_setFindProgressCallback          |  -   -   -   -   +   +   +   +   +
uregex_getFindProgressCallback          |  -   -   -   -   +   +   +   +   +
                                        |
  <unicode/ucal.h>                      |
ucal_openTimeZones                      |
ucal_openCountryTimeZones               |
ucal_getDefaultTimeZone                 |
ucal_setDefaultTimeZone                 |
ucal_getDSTSavings                      |
ucal_getNow                             |
ucal_open                               |
ucal_close                              |
ucal_clone                              |
ucal_setTimeZone                        |
ucal_getTimeZoneDisplayName             |
ucal_inDaylightTime                     |
ucal_setGregorianChange                 |
ucal_getGregorianChange                 |
ucal_getAttribute                       |
ucal_setAttribute                       |
ucal_getAvailable                       |
ucal_countAvailable                     |
ucal_getMillis                          |
ucal_setMillis                          |
ucal_setDate                            |
ucal_setDateTime                        |
ucal_equivalentTo                       |
ucal_add                                |
ucal_roll                               |
ucal_get                                |
ucal_set                                |
ucal_isSet                              |
ucal_clearField                         |
ucal_clear                              |
ucal_getLimit                           |
ucal_getLocaleByType                    |
ucal_getTZDataVersion                   |
ucal_getCanonicalTimeZoneID             |
ucal_getType                            |
ucal_getKeywordValuesForLocale          |
ucal_getDayOfWeekType                   |  -   +   +   +   +   +   +   +   +
ucal_getWeekendTransition               |  -   +   +   +   +   +   +   +   +
ucal_isWeekend                          |  -   +   +   +   +   +   +   +   +
ucal_openTimeZoneIDEnumeration          |  -   -   -   -   +   +   +   +   +
ucal_getFieldDifference                 |  -   -   -   -   +   +   +   +   +
ucal_getTimeZoneID                      |  -   -   -   -   -   -   -   -   +
ucal_getTimeZoneTransitionDate          |  -   -   -   -   -   -   -   -   +
ucal_getWindowsTimeZoneID               |  -   -   -   -   -   -   -   -   +
ucal_getTimeZoneIDForWindowsID          |  -   -   -   -   -   -   -   -   +
                                        |
  <unicode/ucoleitr.h>                  |
ucol_openElements                       |
ucol_keyHashCode                        |
ucol_closeElements                      |
ucol_reset                              |
ucol_next                               |
ucol_previous                           |
ucol_getMaxExpansion                    |
ucol_setText                            |
ucol_getOffset                          |
ucol_setOffset                          |
ucol_primaryOrder                       |
ucol_secondaryOrder                     |
ucol_tertiaryOrder                      |
                                        |
  <unicode/uspoof.h>                    |
uspoof_open                             |
uspoof_close                            |
uspoof_clone                            |
uspoof_setChecks                        |
uspoof_getChecks                        |
uspoof_setAllowedLocales                |
uspoof_getAllowedLocales                |
uspoof_setAllowedChars                  |
uspoof_getAllowedChars                  |
uspoof_check                            |
uspoof_checkUTF8                        |
uspoof_areConfusable                    |
uspoof_areConfusableUTF8                |
uspoof_getSkeleton                      |
uspoof_getSkeletonUTF8                  |
uspoof_openFromSerialized               |  -   +   +   +   +   +   +   +   +
uspoof_openFromSource                   |  -   +   +   +   +   +   +   +   +
uspoof_serialize                        |  -   +   +   +   +   +   +   +   +
uspoof_setRestrictionLevel              |  -   -   -   -   -   -   -   +   +
uspoof_getRestrictionLevel              |  -   -   -   -   -   -   -   +   +
uspoof_getInclusionSet                  |  -   -   -   -   -   -   -   -   +
uspoof_getRecommendedSet                |  -   -   -   -   -   -   -   -   +
                                        |
  <unicode/ubrk.h>                      |
ubrk_open                               |
ubrk_openRules                          |
ubrk_safeClone                          |
ubrk_close                              |
ubrk_setText                            |
ubrk_setUText                           |
ubrk_current                            |
ubrk_next                               |
ubrk_previous                           |
ubrk_first                              |
ubrk_last                               |
ubrk_preceding                          |
ubrk_following                          |
ubrk_getAvailable                       |
ubrk_countAvailable                     |
ubrk_isBoundary                         |
ubrk_getRuleStatus                      |
ubrk_getRuleStatusVec                   |
ubrk_getLocaleByType                    |
ubrk_refreshUText                       |  -   -   -   -   -   +   +   +   +
                                        |
  <unicode/usearch.h>                   |
usearch_open                            |
usearch_openFromCollator                |
usearch_close                           |
usearch_setOffset                       |
usearch_getOffset                       |
usearch_setAttribute                    |
usearch_getAttribute                    |
usearch_getMatchedStart                 |
usearch_getMatchedLength                |
usearch_getMatchedText                  |
usearch_setBreakIterator                |
usearch_getBreakIterator                |
usearch_setText                         |
usearch_getText                         |
usearch_getCollator                     |
usearch_setCollator                     |
usearch_setPattern                      |
usearch_getPattern                      |
usearch_first                           |
usearch_following                       |
usearch_last                            |
usearch_preceding                       |
usearch_next                            |
usearch_previous                        |
usearch_reset                           |
                                        |
  <unicode/uclean.h>                    |
u_init                                  |
u_cleanup                               |
u_setMutexFunctions                     |  +   +   +   +   +   +   -   -   -
u_setAtomicIncDecFunctions              |  +   +   +   +   +   +   -   -   -
u_setMemoryFunctions                    |
                                        |
  <unicode/putil.h>                     |
u_getDataDirectory                      |
u_setDataDirectory                      |
u_charsToUChars                         |
u_UCharsToChars                         |
                                        |
  <unicode/unumsys.h>                   |
unumsys_open                            |  -   -   -   -   -   -   -   -   +
unumsys_openByName                      |  -   -   -   -   -   -   -   -   +
unumsys_close                           |  -   -   -   -   -   -   -   -   +
unumsys_openAvailableNames              |  -   -   -   -   -   -   -   -   +
unumsys_getName                         |  -   -   -   -   -   -   -   -   +
unumsys_isAlgorithmic                   |  -   -   -   -   -   -   -   -   +
unumsys_getRadix                        |  -   -   -   -   -   -   -   -   +
unumsys_getDescription                  |  -   -   -   -   -   -   -   -   +
                                        |
--------------------------------------------------------------------------------
TOTAL                                   | 776 813 813 817 869 880 884 891 930
--------------------------------------------------------------------------------
ICU VERSIONS                            |  44  46  48  49  50  51  52  53  54
 */

#ifndef NDKICU_H
#define NDKICU_H

/**
 * Returns the initialization status of NDK ICU library.
 *  A positive value indiates the ICU version which has been successfully
 *     found and loaded on device;
 *  0 means failure to execute the init function;
 * -1 means invalid ICU data file found on device;
 * -2 means failure to load ICU shared libraries.
 *
 * This function is not mandantory to be called for NDK ICU functionalities.
 */
int ndk_icu_status(void);

#endif
