#!/bin/sh
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# acov is a tool for gathering coverage information from a device and generating
# a report from that information. To use:
#
# 1. sudo apt-get install lcov
# 2. Build application/library with coverage information.
#     * make NATIVE_COVERAGE=true COVERAGE_PATHS='*'
# 3. Push the new binaries to the device with adb sync.
# 4. Run tests with the additional environment variable:
#     * GCOV_PREFIX=/data/misc/trace/testcoverage
# 5. Run `acov /data/misc/trace/testcoverage`.
#
# acov will pull all coverage information from the device, push it to the right
# directories, run lcov, and display the coverage report (currently by opening
# it in your browser).
#

ANDROID_OUT=${OUT_DIR:-out}

if [ "$1" = "--clean" ]; then
  if [ -d "$ANDROID_OUT" ]; then
    find $ANDROID_OUT \( -name '*.gcda' -o -name '*.gcno' \) -delete
  fi
  exit 0
fi

if [ "$1" = "--prep" ]; then
  if [ -d "$ANDROID_OUT" ]; then
    find $ANDROID_OUT -name '*.gcda' -delete
  fi
  exit 0
fi

which lcov >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  echo 'lcov not found: running `sudo apt-get install lcov`'
  sudo apt-get install lcov
fi

adb root
if [ "$1" = "--flush" ]; then
  adb shell kill -37 -1
  shift
fi

cd $ANDROID_BUILD_TOP
FILE=cov.info
DIR=$(mktemp -d covreport-XXXXXX)

adb pull $1/proc/self/cwd/$ANDROID_OUT
shift

EXTRA_ARGS="--gcov-tool=llvm-gcov $@"

lcov -c -d $ANDROID_OUT -o $DIR/$FILE $EXTRA_ARGS
echo "Generating coverage report at $DIR"
genhtml -q -o $DIR $DIR/$FILE
xdg-open $DIR/index.html >/dev/null
